# docker-compose.yml
version: '3.3'

services:
  laracom-demo-cli:
    build: ./demo-cli
    environment:
      MICRO_REGISTRY: "mdns"

  laracom-demo-service:
    build: ./demo-service
    ports:
      - 9091:9091
    environment:
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "mdns"

  laracom-user-service:
    depends_on:
      - laracom-user-db
      - laracom-nats
    build: ./user-service
    ports:
      - 9092:9091
    environment:
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "mdns"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "laracom-nats:4222"
      DB_HOST: "laracom-user-db:3306"
      DB_NAME: "laracom_user"
      DB_USER: "test"
      DB_PASSWORD: "test"
    networks:
      - microservice

  laracom-user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"

  laracom-micro-api:
    image: microhq/micro:latest
    container_name: laracom-micro-api
    environment:
      MICRO_REGISTRY: "mdns"
    links:
      - laracom-user-service
    ports:
      - 8080:8080
    networks:
      - microservice
    command: api --handler=rpc --namespace=laracom.service

  laracom-user-db:
    image: mysql:5.7
    ports:
      - 33061:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "laracom_user"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - microservice

  laracom-nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    restart: always
    networks:
      - microservice

volumes:
  db_data: {}

networks:
  microservice:
      external: true