# docker-compose.yml
version: '3.3'

networks:
  laracom_network:
    external: true

volumes:
  db_user_data: {}
  db_product_data: {}
  grafana_data: {}
  prometheus_data: {}
  etcd_data_1: {}
  etcd_data_2: {}
  etcd_data_3: {}

services:
  laracom-demo-service:
    image: laracom/demoservice
    depends_on:
      - etcd1
      - etcd2
      - etcd3
    environment:
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"
      MICRO_CONFIG_PATH: "laracom/demo.json"
    networks:
      - laracom_network
    deploy:
      mode: replicated
      replicas: 1

  laracom-user-service:
    image: laracom/userservice
    depends_on:
      - laracom-user-db
      - laracom-nats
      - etcd1
      - etcd2
      - etcd3
    environment:
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "laracom-nats:4222"
      DB_HOST: "laracom-user-db:3306"
      DB_NAME: "laracom_user"
      DB_USER: "test"
      DB_PASSWORD: "test"
    networks:
      - laracom_network
    deploy:
      mode: replicated
      replicas: 3

  laracom-product-service:
    image: laracom/productservice
    depends_on:
      - laracom-product-db
      - etcd1
      - etcd2
      - etcd3
      - jaeger
    environment:
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"
      DB_HOST: "laracom-product-db:3306"
      DB_NAME: "laracom_product"
      DB_USER: "product"
      DB_PASSWORD: "test"
      MICRO_LOG_LEVEL: "debug"
    networks:
      - laracom_network
    deploy:
      mode: replicated
      replicas: 3

  laracom-micro-api:
    image: microhq/micro:latest
    environment:
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"
    ports:
      - 8080:8080
    networks:
      - laracom_network
    command: api --handler=rpc --namespace=laracom.service
    deploy:
      placement:
        constraints: [node.role == manager]

  laracom-web-dashboard:
    image: microhq/micro:latest
    environment:
      MICRO_REGISTRY: "etcd"
      MICRO_REGISTRY_ADDRESS: "etcd1:2379,etcd2:2379,etcd3:2379"
    ports:
      - 8082:8082
    networks:
      - laracom_network
    command: web
    deploy:
      placement:
        constraints: [node.role == manager]

  laracom-user-db:
    image: mysql:5.7
    ports:
      - 33061:3306
    volumes:
      - db_user_data:/var/lib/mysql
    environment:
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "laracom_user"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - laracom_network
    deploy:
      placement:
        constraints: [node.role == manager]

  laracom-product-db:
    image: mysql:5.7
    ports:
      - 33062:3306
    volumes:
      - db_product_data:/var/lib/mysql
    environment:
      MYSQL_USER: "product"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "laracom_product"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - laracom_network
    deploy:
      placement:
        constraints: [node.role == manager]

  laracom-nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    networks:
      - laracom_network
    deploy:
      placement:
        constraints: [node.role == manager]

  etcd1:
    image: bitnami/etcd:latest
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_NAME: "etcd1"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd1:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd1:2379"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
    ports:
      - 23791:2379
      - 23801:2380
    networks:
      - laracom_network
    volumes:
      - etcd_data_1:/bitnami/etcd
    deploy:
      placement:
        constraints: [node.role == manager]

  etcd2:
    image: bitnami/etcd:latest
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_NAME: "etcd2"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd2:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd2:2379"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
    ports:
      - 23792:2379
      - 23802:2380
    networks:
      - laracom_network
    volumes:
      - etcd_data_2:/bitnami/etcd
    deploy:
      placement:
        constraints: [node.role == manager]

  etcd3:
    image: bitnami/etcd:latest
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_NAME: "etcd3"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd3:2380"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd3:2379"
      ETCD_INITIAL_CLUSTER_TOKEN: "etcd-cluster"
      ETCD_INITIAL_CLUSTER: "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380"
      ETCD_INITIAL_CLUSTER_STATE: "new"
    ports:
      - 23793:2379
      - 23803:2380
    networks:
      - laracom_network
    volumes:
      - etcd_data_3:/bitnami/etcd
    deploy:
      placement:
        constraints: [node.role == manager]

  e3w:
    image: soyking/e3w:latest
    ports:
      - "8088:8080"
    volumes:
      - ./conf/e3w/config.ini:/app/conf/config.default.ini
    networks:
      - laracom_network
    deploy:
      placement:
        constraints: [node.role == manager]

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./conf/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
    networks:
      - laracom_network
    deploy:
      placement:
        constraints: [node.role == manager]

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - laracom_network
    deploy:
      placement:
        constraints: [node.role == manager]

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9993:9093
    volumes:
      - ./conf/alertmanager/:/etc/alertmanager/
    networks:
      - laracom_network
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    deploy:
      placement:
        constraints: [node.role == manager]

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8083:8080
    networks:
      - laracom_network
    deploy:
      placement:
        constraints: [node.role == manager]

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./conf/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./conf/grafana/config.monitoring
    networks:
      - laracom_network
    deploy:
      placement:
        constraints: [node.role == manager]

  jaeger:
    image: jaegertracing/all-in-one:1.6
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: "9411"
    ports:
      - "5775:5775/udp"
      - "5778:5778"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "9411:9411"
      - "14268:14268"
      - "16686:16686"
    networks:
      - laracom_network
    deploy:
      placement:
        constraints: [node.role == manager]

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8090:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - laracom_network
    deploy:
      placement:
        constraints: [node.role == manager]